; Custom PHP configuration for Laravel
upload_tmp_dir = /var/www/storage/temp
sys_temp_dir = /var/www/storage/temp
session.save_path = /var/www/storage/framework/sessions

; Suppress tempnam() notice
error_reporting = E_ALL & ~E_NOTICE & ~E_STRICT & ~E_DEPRECATED
display_errors = Off
log_errors = On
